{% set version = "0.0.1" %}

package:
  name: hive-thrift-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hive-thrift-py/hive-thrift-py-{{ version }}.tar.gz
  sha256: c0b2554527beb040c8009b7af9f363f0498df2f985746c8dfd6cc41fdce3d6e1

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fb303
    - fb303_scripts
    - hive_metastore
    - hive_serde
    - hive_service
    - queryplan
    - thrift
    - thrift.protocol
    - thrift.reflection
    - thrift.reflection.limited
    - thrift.server
    - thrift.transport

about:
  home: http://hive.apache.org
  license: Apache 2.0
  summary: 'Hive Python Thrift Libs'

extra:
  recipe-maintainers:
    - pmlandwehr
