travis:
  secure:
    BINSTAR_TOKEN: eoJTtTzv61Jx1yH+K4QVejcNixCktTkebPC2TNA27/QrsHZEFk1lFE3CFHpw1TKPoBp7iqS40KBLqg6f9H7gmmMevTVEtoKiHWhJUXG9T5UNjh7y41y1OxATWkIafsVr8wjJ9YVj2zy7Ge6zpmfXLyVfx815CgYUcwOxs5HqBneU2qYiTDBCjkwcObHZt6l4N2RHAOdU+AUD2k5jWAdC2SbGcFzpfggTZYCUq5y4AOTHGVmJNz2JDCDPtQw5KmuH/P0gDfMCivkUFMsUnYOmVTmR7RWu0d6LJM5o1Sxv3mzg5D2cQG6H5bEtowxLWx5VYyXuKDe7NPBlQ5NtGf0WLzU3+DOhfJlafFBdW8vpaxWAwQjWLqVaQtjN5LOmOqXyQtZu3deBAlQEch27gNGJWJilHkqZyvz2uYpvJcvtAuUJHVK9wu83DPoDyFJPucqTDjKC459i2pWJOq9lcWTVLm/puMfzwwQuLo9g6TXLk2SYg43vymN9sPAv+lY9UKMCOBtO+0HlsKRsTtGwDmAvGvllBB7Bfi5RIzJC1cgN+GM0ied1WsqPChjRqFlGW4aI7Po1YahFHm9zDRsJlF8VGY3HmqQ4CwZ2cGYAyKE1L6txqkvRPrXqZE3dXUGcjXuTfhboo0pffNis5wp8ZnV4/Sq/RMFwhUWvSTnc9SFeyMs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
